# -*- coding: utf-8 -*-
"""reading.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15_BAf_IHP03vIScBC12h28vuKdiYKg-h
"""

#Reading from txt file:
# Format: Node1 Node2
# A B
# A C
# B C
# B D
# E F

G_from_file = nx.read_edgelist('edges.txt')
nx.draw(G_from_file, with_labels=True, node_color='lightblue', font_weight='bold')
plt.show()

import networkx as nx

# Unweighted edge list
G = nx.read_edgelist("network.txt", nodetype=int)

# Weighted edge list
Gw = nx.read_edgelist("network.txt", nodetype=int, data=(("weight", float),))

G = nx.read_adjlist("network.txt", nodetype=int)

#adj matrix
A = np.loadtxt("network.txt", dtype=int)
G = nx.from_numpy_array(A)

G = nx.read_gml("network.txt")

import csv

G = nx.Graph()
with open("network.txt") as f:
    reader = csv.reader(f, delimiter=",")  # change delimiter if needed
    for row in reader:
        u, v = row[0], row[1]
        G.add_edge(u, v)

# Read the graph from the GML file
# Note: For integer node IDs, you might need label='id'
G_from_gml = nx.read_gml('network.gml', label='id')
print("Graph loaded from  successfully!")
print("Nodes:", G_from_gml.nodes())
print("Edges:", G_from_gml.edges())

# Draw the graph
nx.draw(G_from_gml, with_labels=True, node_color='lightgreen', font_weight='bold')
plt.show()